"""initial migration

Revision ID: 4200ae2556df
Revises: 
Create Date: 2025-10-28 10:46:31.185085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4200ae2556df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.alter_column('selected_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('course_subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_subjects_course_id_subject_id_key'), type_='unique')
        batch_op.create_unique_constraint('uix_course_subject', ['course_id', 'subject_id'])

    with op.batch_alter_table('question_scale', schema=None) as batch_op:
        batch_op.alter_column('scale_labels',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_scale', schema=None) as batch_op:
        batch_op.alter_column('scale_labels',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('course_subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uix_course_subject', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('course_subjects_course_id_subject_id_key'), ['course_id', 'subject_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.alter_column('selected_options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
